### ISSUE TITLE
What should the client be able to do? 

### ISSUE THREAD

**Issue by chrisK00** [chrisK00/reelzi#10]

**Comment by bschaatsbergen** [comment]
Assuming we are a cinema, a user can book a reservation to watch a specific movie or view what kind of movies are available for a specific date/time.

**Comment by bschaatsbergen** [comment]
- View movies depending on date/time
- Book a ticket for the movies
    -  View available seats and select a specific seat
- Refund a ticket that's booked 30 minutes before the movie starts
- View future releases

**Comment by chrisK00** [comment]
- View movies in a specific category

**Comment by bschaatsbergen** [comment]
- Search for a specific movie

**Comment by bschaatsbergen** [comment]
- Search by category

**Comment by chrisK00** [comment]
- View movies depending on age limit

**Comment by bschaatsbergen** [comment]
Will proceed with defining endpoints and it's requests in #5
