### ISSUE TITLE
Decide which resources to introduce

### ISSUE THREAD

**Issue by bschaatsbergen** [chrisK00/reelzi#2]
Use .NET 5 for your server application when:

You have cross-platform needs.
You're targeting microservices.
You're using Docker containers.
You need high-performance and scalable systems.
You need side-by-side .NET versions per application.

Bare in mind depending on where we want to host our services we need to have some compatibility, e.g. lambda would only support custom runtime containers, perhaps safer to build a .net core 3.1 webapi?

**Comment by chrisK00** [comment]
Sure we can go with 3.1

**Comment by bschaatsbergen** [comment]
Decided to go with core 3.1

**Comment by bschaatsbergen** [comment]
What kind of data storage would you prefer to work with @chrisK00 ? I would suggest [Amazon Aurora](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_AuroraOverview.html)/[RDS MySQL](https://aws.amazon.com/rds/)

**Comment by bschaatsbergen** [comment]
Preferable we can host both APIs on a webserver (virtual machine) via[ Amazon EC2](https://aws.amazon.com/ec2/instance-types/)

**Comment by chrisK00** [comment]
> What kind of data storage would you prefer to work with @chrisK00 ? I would suggest [AWS Aurora](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_AuroraOverview.html)/[RDS MySQL](https://aws.amazon.com/rds/)

is the setup with theese the same as with f.e postgressql in the c# code?
